#!/bin/bash

export TERM=xterm-256color

tput setaf 4
cat <<'END'
 _   _ _____ _     ____  _     _
| | | |_   _| |   |  _ \| |__ (_) __ _ _ __
| |_| | | | | |   | |_) | '_ \| |/ _` | '_ \
|  _  | | | | |___|  _ <| |_) | | (_| | | | |
|_| |_| |_| |_____|_| \_\_.__/|_|\__,_|_| |_|
END

tput setaf 7
cat <<'END'
            Raspbian Image (GIT Rev: __GITREV__)
            https://github.com/semiversus/htlrbian

END
